# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKApp1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 

  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'SwiftKeychainWrapper'
  pod 'DynamicJSON'
# pod 'Firebase/Auth'
  pod 'Firebase/Database'



end
